name: Deploy to DigitalOcean

on: [push]

jobs:
  Create-Deployment-Artifacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Compile CSS and Javascript
          run: |
            npm ci
            npm run prod
   